seed_everything: 42

trainer:
  max_epochs: 50
  accelerator: auto
  devices: 1

model:
  class_path: phast.model.building_phast
  init_args:
    backbone:        
    decoder: 

data:
  class_path: phast.dataloader.base_loader
  init_args:


optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.0

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: ${trainer.max_epochs} 
    eta_min: 0.0
